steps:
# Step 1: Build the Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/jorgeacruz-pf-dev/challenge3-repogcp/my-build:prod1', '.' ]

# Step 2: Push the image to the Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/jorgeacruz-pf-dev/challenge3-repogcp/my-build:prod1' ]

steps:
- name: 'python'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']

# Step 3: Deployment to Cloud Run after image is pushed
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'challenge3-test'
  - '--image'
  - 'us-central1-docker.pkg.dev/jorgeacruz-pf-dev/challenge3-repogcp/my-build:prod1'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
options:
 logging: CLOUD_LOGGING_ONLY
 pool:
   name: 'projects/jorgeacruz-pf-dev/locations/us-central1/workerPools/private-challenge3'
